CC = gcc
LD = ld
LDFILE = ld_script.ld
OBJCOPY = objcopy
DUMP = objdump

all: bootsect.img

bootsect.img: bootsect.bin hellosect.bin
	@dd if=/dev/zero of=empty_floppy.img bs=512 count=2880
	@dd if=bootsect.bin of=bootsect.img bs=512 count=1
	@dd if=hellosect.bin of=bootsect.img skip=0 seek=1 bs=512 count=1
	@dd if=empty_floppy.img of=bootsect.img skip=2 seek=2 bs=512 count=2878

bootsect.bin: bootsect.elf
	@$(OBJCOPY) -R .pdr -R .comment -R .note -S -O binary bootsect.elf bootsect.bin

bootsect.elf: bootsect.o
	$(LD) bootsect.o -o bootsect.elf -e c -T$(LDFILE)

bootsect.o: bootsect.s
	$(CC) -c bootsect.s

hellosect.bin: hellosect.elf
	@$(OBJCOPY) -R .pdr -R .comment -R .note -S -O binary hellosect.elf hellosect.bin

hellosect.elf: hellosect.o
	$(LD) hellosect.o -o hellosect.elf -e c -T$(LDFILE)

hellosect.o: hellosect.s
	$(CC) -c hellosect.s

dump: bootsect.dump hellosect.dump

bootsect.dump: bootsect.bin
	$(DUMP) -D -b binary -mi386 -M addr16 -M data16 bootsect.bin > bootsect.dump

hellosect.dump: hellosect.bin
	$(DUMP) -D -b binary -mi386 -M addr16 -M data16 hellosect.bin > hellosect.dump

clean:
	@rm -rf bootsect.o bootsect.elf bootsect.bin bootsect.img bootsect.dump
	@rm -rf hellosect.o hellosect.elf hellosect.bin hellosect.img hellosect.dump
	@rm -rf empty_floppy.img
